### ISSUE TITLE
Spotify Friends Menu Not working

### ISSUE THREAD

**Issue by Silverarmor** [Riddim/adblock-Spotify#6]
When enabled, spotify friends menu doesn't show any friends

**Comment by Riddim** [comment]
You mean this panel?
![image](https://user-images.githubusercontent.com/5503640/51606957-a08dd480-1f13-11e9-8562-c4f628820884.png)
I'm currently not using this feature. So to be honest I don't know.

**Comment by ghost** [comment]
Refer to issue #10 , problem solved.
