### ISSUE TITLE
Does not work with some asian album

### ISSUE THREAD

**Issue by popeyaho001** [Riddim/adblock-Spotify#7]
Link album: https://open.spotify.com/album/3AM7DpKXpRix93MY17OvxN?si=AIBCipYlR3qkvrJPsdbdtQ

Image: https://i.imgur.com/kVuTu0Z.png

But after run reset bat file, show ads again, they can play again, can you fix, thank you so much!

EDIT: remove some host
https://i.imgur.com/vog0IFI.png
seems to play available again, and keep watching, thank you!

EDIT 2: still doesn't work some tracks

**Comment by Riddim** [comment]
Yeah I noticed it today as well. I will look into this this weekend. Probably most songs are blocked(except for all the songs that cached on your computer.

**Comment by popeyaho001** [comment]
Yea. I'm waiting for you!

**Comment by Riddim** [comment]
try it now

**Comment by popeyaho001** [comment]
seems ok, had a panel, but it's fine
https://i.imgur.com/Uym65p9.png

**Comment by Riddim** [comment]
That is normal. It never blocked the panel

**Comment by popeyaho001** [comment]
well, had audio promote premium xD
https://i.imgur.com/OuJUqJx.png

**Comment by Riddim** [comment]
oh mm. Well I'll be using spotify today. Hopefully I fix it today.

**Comment by popeyaho001** [comment]
yeah, thank you so much, just add something to get cached and block ads again, hmmm, seems not good

> @echo off
> taskkill /IM Spotify.exe /F
> 
> xcopy /s "%~dp0resethosts" "C:\Windows\System32\drivers\etc\hosts" /y
> 
> start "Spotify.exe" "C:\Users\x\AppData\Roaming\Spotify\Spotify.exe"
> 
> timeout /T 15 /nobreak >nul
> 
> taskkill /IM Spotify.exe /F
> 
> xcopy /s "%~dp0hosts" "C:\Windows\System32\drivers\etc\hosts" /y
> 
> start "Spotify.exe" "C:\Users\x\AppData\Roaming\Spotify\Spotify.exe"
>

**Comment by Riddim** [comment]
mmm do you have another example? I deleted all the cache and restored the original hosts. But I can't seem to replicate the problem... Actually everything seems to work fine now.

**Comment by popeyaho001** [comment]
https://open.spotify.com/artist/433uyUQDYJGlNoFMiIM0wE?si=DFU8uo64TDOPYw1Z_FqsIg

here you go

**Comment by Raalouf** [comment]
Add one title you've never listen to your favorites and it won't show (unless you remove spclient.wg.spotify.com)

**Comment by ghost** [comment]
Refer to issue #10 , problem solved.
