### ISSUE TITLE
Some songs/albums stop working

### ISSUE THREAD

**Issue by FearMyCharm** [Riddim/adblock-Spotify#8]
It removes ads but in the end it stops working properly, i have to reset and block again to make them work

**Comment by Riddim** [comment]
Yeah, the issue arose 2 weeks ago. I did not have the time to fix it. For now, remove spclient.wg.spotify.com from the host file... You will get some ads though....

**Comment by FearMyCharm** [comment]
It's a bit annoying but everything works if you use playlists (dont know if you are aware). So ive been making playlists to listen without problems ^^

**Comment by Riddim** [comment]
Ah oke.! I initially thought it has something to do with caching. I will look into it this weekend again. I will keep you posted.

**Comment by anoop-b** [comment]
I Use Little Snitch, I turn off the network filter for a second and then turn on again,  the song/album plays without any ads. hope it helps someone.

**Comment by intika** [comment]
i am sharing a premium family subscription (usa) for 3,29€ per month on [digishare](https://play.google.com/store/apps/details?id=io.digishare) if any one interested

**Comment by ghost** [comment]
Refer to issue #10 , problem solved.
